require("xtan.plugins-setup")
require("xtan.core.options")
require("xtan.core.keymaps")
-- require("xtan.core.colorscheme")
require("xtan.plugins.cmp")
require("xtan.plugins.comment")
require("xtan.plugins.bufferline")
require("xtan.plugins.nvim-tree")
require("xtan.plugins.lualine")
require("xtan.plugins.telescope")
require("xtan.plugins.nvim-cmp")
require("xtan.plugins.lsp.mason")
require("xtan.plugins.lsp.lspsaga")
require("xtan.plugins.lsp.lspconfig")
require("xtan.plugins.lsp.null-ls")
require("xtan.plugins.autopairs")
require("xtan.plugins.treesitter")
require("xtan.plugins.gitsigns")
require("xtan.plugins.nvim-magic")
require("xtan.plugins.alpha")
require("xtan.plugins.vgit")
require("xtan.plugins.toggleterm")
require("xtan.plugins.neosolarized")

-- colorscheme
vim.o.background = "dark" -- or "light" for light mode
vim.cmd([[colorscheme neosolarized]])
