#!/bin/sh
sudo rmmod btusb && sudo rmmod btintel 
sudo modprobe btusb && sudo modprobe btintel
sleep 1
bluetoothctl connect E4:41:22:96:FD:8B
notify-send "Successfully Connected to OnePlue Bullets Z"


