#!/bin/sh
sudo rmmod btusb 
sleep 1
sudo rmmod btintel 
sleep 1
sudo modprobe btusb && sudo modprobe btintel
sleep 1
bluetoothctl power off 
sleep 1 
bluetoothctl power on
sleep 1
bluetoothctl remove  E4:41:22:96:FD:8B
sleep 1
bluetoothctl scan on
sleep 1
bluetoothctl pair E4:41:22:96:FD:8B
sleep 1 
bluetoothctl trust E4:41:22:96:FD:8B
sleep 1 
bluetoothctl connect E4:41:22:96:FD:8B
notify-send "Successfully Connected to OnePlue Bullets Z"


