#!/bin/sh
#number=12
#for((i=1; i<=$number; i++));
#do 
 # xrandr --output eDP --mode 1366x768 --rate 40
 # sleep 2
 # xrandr --output eDP --mode 1366x768 --rate 60
#done 



xrandr --output eDP --mode 1366x768 --rate 40

